services:
  app:
    build: .
    container_name: user_management_app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  db:
    image: mysql:8.4.4
    container_name: user_management_db
    ports:
      - "${DB_HOST_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local